resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s        
    instances:
      client: 
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 6s
    instances:
      client:
        base-config: default      